name: DevSecOps End to End Pipeline

on: 
  push:
    branches: [main]
  workflow_dispatch:
     
jobs:
    check-code-quality:
      uses: ./.github/workflows/code-quality.yml

    check-secrets:
      uses: ./.github/workflows/secrets-scan.yml

    check-dependency:
      uses: ./.github/workflows/dependency-scan.yml
            
    check-docker-lint:
      uses: ./.github/workflows/docker-lint.yml

    docker-build-and-push:
      uses: ./.github/workflows/docker-build-push.yml
            
    image-scan:
      uses: ./.github/workflows/image-scan.yml