# My first Workflow
name: first workflow

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: first build
        run: sudo apt-get update && echo "update successful"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: first test
        run: df -h

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: first deploy
        run: echo "Deployed successfully"
