name: docker image scan

on:
    workflow_call:
      
jobs:
    scan-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                    username: ${{ vars.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Scan Docker image by trivy
              uses: aquasecurity/trivy-action@0.70.0
              with:
                  severity: CRITICAL
                  image-ref: ${{ vars.DOCKERHUB_USERNAME }}/github-actions--app:${{ github.ref_name }}
                  exit-code: '1'
