name: Portfolio

on:
    push:
        branches: [main]
        paths:
            - '**.html'
            
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            # get access to the repository
            # clones or checks out the code where thid workflow is written
            # STEP 1
            - name: Checkout code
              uses: actions/checkout@v4

            # Setup github pages
            # STEP 2
            - name: Setup Github pages
              uses: actions/configure-pages@v4

            # Static code artifacts
            # STEP 3
            - name: upload static files
              uses: actions/upload-pages-artifact@v4

            # Deploy to github pages
            # STEP 4
            - name: Deploy to github pages
              uses: actions/deploy-pages@v4
